
import 'Tone.dart';

class Constant {
  static List toneList = [
    Tone("a", "あ", "ア"),
    Tone("i", "い", "イ"),
    Tone("u", "う", "ウ"),
    Tone("e", "え", "エ"),
    Tone("o", "お", "オ"),
    Tone("ka", "か", "カ"),
    Tone("ki", "き", "キ"),
    Tone("ku", "く", "ク"),
    Tone("ke", "け", "ケ"),
    Tone("ko", "こ", "コ"),
    Tone("sa", "さ", "サ"),
    Tone("shi", "し", "シ"),
    Tone("su", "す", "ス"),
    Tone("se", "せ", "セ"),
    Tone("so", "そ", "ソ"),
    Tone("ta", "た", "タ"),
    Tone("chi", "ち", "チ"),
    Tone("tsu", "つ", "ツ"),
    Tone("te", "て", "テ"),
    Tone("to", "と", "ト"),
    Tone("na", "な", "ナ"),
    Tone("ni", "に", "ニ"),
    Tone("nu", "ぬ", "ヌ"),
    Tone("ne", "ね", "ネ"),
    Tone("no", "の", "ノ"),
    Tone("ha", "は", "ハ"),
    Tone("hi", "ひ", "ヒ"),
    Tone("fu", "ふ", "フ"),
    Tone("he", "へ", "ヘ"),
    Tone("ho", "ほ", "ホ"),
    Tone("ma", "ま", "マ"),
    Tone("mi", "み", "ミ"),
    Tone("mu", "む", "ム"),
    Tone("me", "め", "メ"),
    Tone("mo", "も", "モ"),
    Tone("ya", "や", "ヤ"),
    Tone("", "", ""),
    Tone("yu", "ゆ", "ユ"),
    Tone("", "", ""),
    Tone("yo", "よ", "ヨ"),
    Tone("ra", "ら", "ラ"),
    Tone("ri", "り", "リ"),
    Tone("ru", "る", "ル"),
    Tone("re", "れ", "レ"),
    Tone("ro", "ろ", "ロ"),
    Tone("wa", "わ", "ワ"),
    Tone("", "", ""),
    Tone("", "", ""),
    Tone("", "", ""),
    Tone("wo", "を", "ヲ"),
  ];

}